const Ziggy = {"url":"http:\/\/admanager.test","port":null,"defaults":{},"routes":{"dashboard":{"uri":"dashboard","methods":["GET","HEAD"]},"adsDashboard":{"uri":"manage\/ads","methods":["GET","HEAD"]},"sectionsDashboard":{"uri":"manage\/sections","methods":["GET","HEAD"]},"mediaDashboard":{"uri":"manage\/media","methods":["GET","HEAD"]},"listSections":{"uri":"sections\/list","methods":["GET","HEAD"]},"createSectionPage":{"uri":"sections\/create","methods":["GET","HEAD"]},"createSection":{"uri":"sections\/new","methods":["POST"]},"deleteSection":{"uri":"sections\/delete","methods":["POST"]},"updateSection":{"uri":"sections\/update","methods":["POST"]},"listMedia":{"uri":"media\/list","methods":["GET","HEAD"]},"getMedia":{"uri":"media\/get\/{id}","methods":["GET","HEAD"]},"storeMedia":{"uri":"media\/store","methods":["POST"]},"deleteMedia":{"uri":"media\/delete","methods":["POST"]},"listAds":{"uri":"ads\/list","methods":["GET","HEAD"]},"createAdPage":{"uri":"ads\/create","methods":["GET","HEAD"]},"register":{"uri":"register","methods":["GET","HEAD"]},"login":{"uri":"login","methods":["GET","HEAD"]},"password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},"password.email":{"uri":"forgot-password","methods":["POST"]},"password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"]},"password.update":{"uri":"reset-password","methods":["POST"]},"verification.notice":{"uri":"verify-email","methods":["GET","HEAD"]},"verification.verify":{"uri":"verify-email\/{id}\/{hash}","methods":["GET","HEAD"]},"verification.send":{"uri":"email\/verification-notification","methods":["POST"]},"password.confirm":{"uri":"confirm-password","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
